version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddemdb
    volumes:
      - /home/mysql/data:/var/lib/mysql

  kaddem-devops:
    image: ferjanihejer905/kaddem-devops:67
    container_name: kaddem-devops
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/kaddemdb
    ports:
      - 8089:8089
    depends_on:
      - mysqldb