version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /home/mysql/data:/var/lib/mysql